### PR TITLE
Avocado Network Faucet

### PR DESCRIPTION
**Pull request by NFhbar**
# Updated to v2.0.0
# AVO Faucet v2.0.0

## Version
[v2.0.0](https://github.com/NFhbar/smart-contract-faucet/releases) as described in [#4](https://github.com/AvocadoNetwork/governance/issues/4).

## Implementation
```Faucet.sol``` implements 3 token drip methods with time locks:

```drip1000Token()``` time lock: 1 hour
```drip2000Token()``` time lock: 2 hour
```drip5000Token()``` time lock: 5 hour

Rinkeby Instance [here](https://rinkeby.etherscan.io/address/0x8c2451d9bebc7c18ca89fdf7db8692d51605c04b#code).

Full description available in [README](https://github.com/NFhbar/smart-contract-faucet/blob/master/README.md).

### Travis CI
[Travis CI](https://travis-ci.org/NFhbar/smart-contract-faucet) for building and testing. If pull request accepted, log into Travis account, enable repo, add environment variables as required in [truffle.js](https://github.com/NFhbar/smart-contract-faucet/blob/master/truffle.js) and update badge in [README](https://github.com/NFhbar/smart-contract-faucet/blob/master/README.md) to point to new Travis build.

### Coveralls
[Coveralls](https://coveralls.io/github/NFhbar/smart-contract-faucet) for coverage reports. If pull request accepted, log into Coveralls account, enable repo, and update badge in [README](https://github.com/NFhbar/smart-contract-faucet/blob/master/README.md) to point to new Coveralls report.

## Ownership
Faucet was deployed using a fresh address for which the private key is available upon request.

### CODE REVIEW

**Comment by peter-evans** [comment]
This looks great! Please just give us a bit of time to review it.
Do you have any suggestions for how to transmit the private key for the address?

**Comment by NFhbar** [comment]
@peter-evans of course. Please let me know of any modifications or improvements that you would like to see, I tested it extensively but there is always room for improvement. 
For the key we can do encrypted email, and you can always change ownership as soon as you get the key rendering the deployer account useless. 

Edit: you could also just deploy a new instance from any address that you own and I can turn this faucet off, whatever you prefer.

**Review by peter-evans — APPROVED** [review]
I tested it a little on testnet and it seems to work great. I wasn't expecting a full suite of tests for this. Thank you!

**Comment by peter-evans** [comment]
How about sending the private key via protonmail. Does that work for you?

**Comment by NFhbar** [comment]
@peter-evans great! I usually write the test suite first then make the contract pass the tests :)

I sent you the private key, please confirm that you received it.

**Comment by peter-evans** [comment]
@NFhbar I received the private key and transferred ownership of the contract. Thank you!

**Comment by peter-evans** [comment]
After @agro1986 has completed his review we'll merge and complete the issue.

**Comment by agro1986** [comment]
Thanks for the hard work. Looks great :). Some suggestions:

1) You're only calling the transfer method of avoInstance anyway, so actually avoInstance doesn't need to be a reference to AvocadoToken but can refer to a generic ERC20Basic. Can you change it to be so?

The benefit is deploying will be much cheaper because you don't need to deploy the definition of AvocadoToken to the blockchain which is quite a long code.

2) checkStatus writes to the blockchain which wastes gas (writing is an expensive operation). Perhaps you can make it just return the result as bool. (mapping(address => addressStatus) status can be simplified to mapping(address => uint256) which just stores the last access time)

After those 2 changes and the redeployment @peter-evans can complete the issue.

**Comment by NFhbar** [comment]
@agro1986 thanks for the review, those are great suggestions! A couple questions:

1. sounds good. I can import ```ERC20Basic.sol``` instead, however by making the Faucet generic, should I also change the name of the functions, constants, and events to reflect this:
```function drip1000AVO``` -> ```function drip1000Tokens()``` 
```function drip2000AVO``` -> ```function drip2000Tokens()``` 
```function drip5000AVO``` -> ```function drip5000Tokens()``` 
etc...
Note: if these change, Faucet release will be v2.0.0 since API will not be backwards compatible.

2. great catch!

**Comment by agro1986** [comment]
@NFhbar agree with method name change :). Looking forward to the redeployed contract.

**Comment by NFhbar** [comment]
@agro1986 excellent, v2.0.0 coming in a few hours!

**Comment by NFhbar** [comment]
v2.0.0 is now live, please review :)

**Comment by peter-evans** [comment]
Looks good. Thank you! I got confirmation from @agro1986 too.

**Comment by peter-evans** [comment]
Successfully transferred ownership of the new contract.

**Comment by NFhbar** [comment]
Great! Remember to set up Travis and Coveralls and to point them to the repo in the README.
I am also gonna write a quick Medium article, should get the repo some nice traffic.

**Comment by peter-evans** [comment]
```process.env['RINKEBY_PRIVATE_KEY']```
Just to clarify. This private key should be the private key of the address that is owner of the contract on Rinkeby?

**Comment by NFhbar** [comment]
Yeah. It doesn't have to be but I would use that one, also remember to add the `.env` file to `.gitignore`
Edit: never mind `.gitignore` already includes that file.

**Comment by peter-evans** [comment]
Updated Travis and Coveralls. Thanks!

**Pull request merged**
